module.exports = {
  theme: {
    extend: {},
    cursor: {
      auto: 'auto',
      default: 'default',
      pointer: 'pointer',
      wait: 'wait',
      text: 'text',
      move: 'move',
      'not-allowed': 'not-allowed',
      'ns-resize': 'ns-resize',
      'ew-resize': 'ew-resize',
      'nesw-resize': 'nesw-resize',
      'nwse-resize': 'nwse-resize',
      grab: 'grab',
      grabbing: 'grabbing',
    },
    scale: {
      '0': '0',
      '25': '.25',
      '50': '.5',
      '75': '.75',
      '90': '.9',
      '100': '1',
      '125': '1.25',
      '150': '1.5',
    },
    minWidth: {
      1: '1rem',
      2: '2rem',
      3: '3rem',
      4: '4rem',
      5: '5rem',
      6: '6rem',
      7: '7rem',
      8: '8rem',
      9: '9rem',
      10: '10rem',
    }
  },
  variants: {
    margin: ['responsive', 'hover', 'focus'],
  },
  plugins: [],
};
